### ISSUE TITLE
bug while starting the server

### ISSUE THREAD

**Issue by myst213** [Axwabo/slocLoader#11]
i tride instaling slocloader on my exiled server and i got this bug

`> [20:12:43] [ERROR] [Exiled.Loader] Error while initializing plugin slocLoader (at )! System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.`

**Comment by Axwabo** [comment]
Could you provide the entire stack trace?
Make sure you've installed the EXILED version along with [Axwabo.Helpers](https://github.com/Axwabo/SCPSL-Helpers)
