### ISSUE TITLE
Sloc + MER = no no D:

### ISSUE THREAD

**Issue by BenFRC5147** [Axwabo/slocLoader#7]
I know, I know, who in their right mind would need two different map editor plugins on one server?

Me!

please, fix the issue where having MER installed breaks Slocs, I beg, I use plugins that use both Sloc and MER, and I'd be very happy man not to have to pick which one I stick with, because choosing is hard!

I beg, my Cats beg, even the mailman begs, fix this issue!

LA Log when occur
[2023-09-24 23:52:03.190 +00:00] [STDOUT] SpawnObject Empty (UnityEngine.GameObject) has no NetworkIdentity. Please add a NetworkIdentity to Empty (UnityEngine.GameObject)

**Comment by Axwabo** [comment]
@BenFRC5147 I see the issue, it will be diagnosed. This incompatibility requires looking at the MER source code.
